Default to not include MMS part sub_ids in import
Some MMS part metadata apparently contain a sub_id field (despite the
absence of any mention of this in the API documentation at
https://developer.android.com/reference/android/provider/Telephony.Mms.Part),
and attempting to import these sub_ids can cause the app to crash with a
FileNotFoundException: No entry for content.

This is probably related to https://github.com/tmo1/sms-ie/issues/128.
In any event, this commit fixes the problem by extending the solution to
that issue (c56fa0e7d65cf44b69e3698bd3fe9e38a81850a9) to MMS part
metadata sub_ids.

Addresses: #142
Related: #128