Add r8/proguard rules for JNA
JNA's Android .aar artifact doesn't include any r8/proguard rules.
According to their FAQ [1], application developers are expected to copy
and paste the 4 rules into their proguard configs. Without these rules,
SodiumAndroid() initialization would fail because JNA's initialization
can't find the fields it needed via reflection with r8 renaming fields
to single letter names.

    java.lang.UnsatisfiedLinkError: Can't obtain peer field ID for class com.sun.jna.Pointer

This only affected release builds since debug builds don't have r8
enabled.

[1] https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md#jna-on-android

Fixes: #357

Signed-off-by: Andrew Gunnerson <accounts+github@chiller3.com>